package com.github.blindpirate.gogradle.core

import org.junit.Test

import java.nio.file.Paths

import static com.github.blindpirate.gogradle.core.StandardGolangPackage.of

class StandardGolangPackageTest {
    StandardGolangPackage standardGolangPackage = of(Paths.get('go/ast'))

    @Test
    void 'rootPath of a standard package should be itself'() {
        assert standardGolangPackage.rootPathString == 'go/ast'
    }

    @Test
    void 'root path of standard package should be identical to path'() {
        assert standardGolangPackage.rootPath == standardGolangPackage.path
    }

    @Test
    void 'toString should succeed'() {
        assert standardGolangPackage.toString() == "StandardGolangPackage{path='go/ast'}"
    }

    @Test
    void 'package generated by standard package should also be standard'() {
        assert standardGolangPackage.resolve('go').get() instanceof StandardGolangPackage
        assert standardGolangPackage.resolve('go/ast/ast').get() instanceof StandardGolangPackage
    }
}
